/* Generated By:JavaCC: Do not edit this line. MooplParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MooplParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROC = 8;
  /** RegularExpression Id. */
  int FUN = 9;
  /** RegularExpression Id. */
  int CLASS = 10;
  /** RegularExpression Id. */
  int EXTENDS = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int ARRAYOF = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int OUTPUT = 21;
  /** RegularExpression Id. */
  int LENGTH = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int SELF = 25;
  /** RegularExpression Id. */
  int NEW = 26;
  /** RegularExpression Id. */
  int LPAREN = 27;
  /** RegularExpression Id. */
  int RPAREN = 28;
  /** RegularExpression Id. */
  int SEMICOL = 29;
  /** RegularExpression Id. */
  int LSQBR = 30;
  /** RegularExpression Id. */
  int RSQBR = 31;
  /** RegularExpression Id. */
  int NOT = 32;
  /** RegularExpression Id. */
  int ISNULL = 33;
  /** RegularExpression Id. */
  int COMM = 34;
  /** RegularExpression Id. */
  int LCBR = 35;
  /** RegularExpression Id. */
  int RCBR = 36;
  /** RegularExpression Id. */
  int PERIOD = 37;
  /** RegularExpression Id. */
  int OBJECT = 38;
  /** RegularExpression Id. */
  int EQUALS = 39;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 40;
  /** RegularExpression Id. */
  int OP = 41;
  /** RegularExpression Id. */
  int ID = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"proc\"",
    "\"fun\"",
    "\"class\"",
    "\"extends\"",
    "\"return\"",
    "\"arrayof\"",
    "\"boolean\"",
    "\"int\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"output\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"self\"",
    "\"new\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"!\"",
    "\"isnull\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"object\"",
    "\"=\"",
    "<INTEGER_LITERAL>",
    "<OP>",
    "<ID>",
  };

}
