/* Generated By:JavaCC: Do not edit this line. MooplParser.java */
  import syntaxtree.*;
  import syntaxtree.interp.*;
  import java.util.List;
  import java.util.LinkedList;
  public class MooplParser implements MooplParserConstants {

  final public void testTokens() throws ParseException {
  Token t;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROC:
      case FUN:
      case CLASS:
      case EXTENDS:
      case RETURN:
      case ARRAYOF:
      case BOOLEAN:
      case INT:
      case IF:
      case THEN:
      case ELSE:
      case WHILE:
      case DO:
      case OUTPUT:
      case LENGTH:
      case TRUE:
      case FALSE:
      case SELF:
      case NEW:
      case LPAREN:
      case RPAREN:
      case SEMICOL:
      case LSQBR:
      case RSQBR:
      case NOT:
      case ISNULL:
      case COMM:
      case LCBR:
      case RCBR:
      case PERIOD:
      case OBJECT:
      case EQUALS:
      case INTEGER_LITERAL:
      case OP:
      case ID:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROC:
      case FUN:
      case CLASS:
      case EXTENDS:
      case RETURN:
      case ARRAYOF:
      case BOOLEAN:
      case INT:
      case IF:
      case THEN:
      case ELSE:
      case WHILE:
      case DO:
      case OUTPUT:
      case LENGTH:
      case TRUE:
      case FALSE:
      case SELF:
      case NEW:
      case LPAREN:
      case RPAREN:
      case SEMICOL:
      case LSQBR:
      case RSQBR:
      case NOT:
      case ISNULL:
      case COMM:
      case LCBR:
      case RCBR:
      case PERIOD:
      case OBJECT:
      case EQUALS:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PROC:
          t = jj_consume_token(PROC);
          break;
        case FUN:
          t = jj_consume_token(FUN);
          break;
        case CLASS:
          t = jj_consume_token(CLASS);
          break;
        case EXTENDS:
          t = jj_consume_token(EXTENDS);
          break;
        case RETURN:
          t = jj_consume_token(RETURN);
          break;
        case ARRAYOF:
          t = jj_consume_token(ARRAYOF);
          break;
        case BOOLEAN:
          t = jj_consume_token(BOOLEAN);
          break;
        case INT:
          t = jj_consume_token(INT);
          break;
        case IF:
          t = jj_consume_token(IF);
          break;
        case THEN:
          t = jj_consume_token(THEN);
          break;
        case ELSE:
          t = jj_consume_token(ELSE);
          break;
        case WHILE:
          t = jj_consume_token(WHILE);
          break;
        case DO:
          t = jj_consume_token(DO);
          break;
        case OUTPUT:
          t = jj_consume_token(OUTPUT);
          break;
        case LENGTH:
          t = jj_consume_token(LENGTH);
          break;
        case TRUE:
          t = jj_consume_token(TRUE);
          break;
        case FALSE:
          t = jj_consume_token(FALSE);
          break;
        case SELF:
          t = jj_consume_token(SELF);
          break;
        case NEW:
          t = jj_consume_token(NEW);
          break;
        case LPAREN:
          t = jj_consume_token(LPAREN);
          break;
        case RPAREN:
          t = jj_consume_token(RPAREN);
          break;
        case SEMICOL:
          t = jj_consume_token(SEMICOL);
          break;
        case LSQBR:
          t = jj_consume_token(LSQBR);
          break;
        case RSQBR:
          t = jj_consume_token(RSQBR);
          break;
        case NOT:
          t = jj_consume_token(NOT);
          break;
        case ISNULL:
          t = jj_consume_token(ISNULL);
          break;
        case COMM:
          t = jj_consume_token(COMM);
          break;
        case LCBR:
          t = jj_consume_token(LCBR);
          break;
        case RCBR:
          t = jj_consume_token(RCBR);
          break;
        case PERIOD:
          t = jj_consume_token(PERIOD);
          break;
        case OBJECT:
          t = jj_consume_token(OBJECT);
          break;
        case EQUALS:
          t = jj_consume_token(EQUALS);
          break;
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        System.out.println("Recognised as valid token: " + t.image);
        break;
      case INTEGER_LITERAL:
        t = jj_consume_token(INTEGER_LITERAL);
        System.out.println("Recognised as INTEGER_LITERAL: " + t.image);
        break;
      case ID:
        t = jj_consume_token(ID);
        System.out.println("Recognised as ID: " + t.image);
        break;
      case OP:
        t = jj_consume_token(OP);
         System.out.println("Recognised as OP: " + t.image);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public Program nt_Program() throws ParseException {
  ProcDecl pd;
  ClassDecl cd;
  List<ProcDecl> pds = new LinkedList<ProcDecl>();
  List<ClassDecl> cds = new LinkedList<ClassDecl>();
    label_2:
    while (true) {
      pd = nt_ProcDecl();
                    pds.add(pd);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PROC:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      cd = nt_ClassDecl();
                     cds.add(cd);
    }
    jj_consume_token(0);
   {if (true) return new Program(pds, cds);}
    throw new Error("Missing return statement in function");
  }

  final public ClassDecl nt_ClassDecl() throws ParseException {
  Token t;
  Token t2;
  FieldDecl fd;
  MethodDecl md;
  List<FieldDecl> fdl = new LinkedList<FieldDecl>();
  List<MethodDecl> mdl = new LinkedList<MethodDecl>();
    if (jj_2_1(3)) {
      jj_consume_token(CLASS);
      t = jj_consume_token(ID);
      jj_consume_token(LCBR);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ARRAYOF:
        case BOOLEAN:
        case INT:
        case ID:
          ;
          break;
        default:
          jj_la1[5] = jj_gen;
          break label_4;
        }
        fd = nt_FieldDecl();
                                           fdl.add(fd);
      }
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PROC:
        case FUN:
          ;
          break;
        default:
          jj_la1[6] = jj_gen;
          break label_5;
        }
        md = nt_MethodDecl();
                                                                              mdl.add(md);
      }
      jj_consume_token(RCBR);
                                                                                                    {if (true) return new ClassDeclSimple(t.image, fdl, mdl);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        jj_consume_token(CLASS);
        t = jj_consume_token(ID);
        jj_consume_token(EXTENDS);
        t2 = jj_consume_token(ID);
        jj_consume_token(LCBR);
        label_6:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case ARRAYOF:
          case BOOLEAN:
          case INT:
          case ID:
            ;
            break;
          default:
            jj_la1[7] = jj_gen;
            break label_6;
          }
          fd = nt_FieldDecl();
        }
        label_7:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PROC:
          case FUN:
            ;
            break;
          default:
            jj_la1[8] = jj_gen;
            break label_7;
          }
          md = nt_MethodDecl();
        }
        jj_consume_token(RCBR);
                                                                                          {if (true) return new ClassDeclExtends(t.image, t2.image,fdl,mdl);}
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public MethodDecl nt_MethodDecl() throws ParseException {
  MethodDecl md;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PROC:
      md = nt_ProcDecl();
                     {if (true) return md;}
      break;
    case FUN:
      md = nt_FunDecl();
                    {if (true) return md;}
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public FunDecl nt_FunDecl() throws ParseException {
  Token t;
  Type type;
  Exp e;
  List<Formal> fl;
  List<Stm> sl = new LinkedList<Stm>();
  Stm s;
    jj_consume_token(FUN);
    type = nt_Type();
    t = jj_consume_token(ID);
    jj_consume_token(LPAREN);
    fl = nt_FormalList();
    jj_consume_token(RPAREN);
    jj_consume_token(LCBR);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARRAYOF:
      case BOOLEAN:
      case INT:
      case IF:
      case WHILE:
      case OUTPUT:
      case TRUE:
      case FALSE:
      case SELF:
      case NEW:
      case LPAREN:
      case NOT:
      case ISNULL:
      case LCBR:
      case INTEGER_LITERAL:
      case ID:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_8;
      }
      s = nt_Statement();
                                                                                            sl.add(s);
    }
    jj_consume_token(RETURN);
    e = nt_Exp();
    jj_consume_token(SEMICOL);
    jj_consume_token(RCBR);
   {if (true) return new FunDecl(type, t.image, fl, sl, e);}
    throw new Error("Missing return statement in function");
  }

  final public ProcDecl nt_ProcDecl() throws ParseException {
  Token t;
  Stm s;
  List<Formal> fl;
  List<Stm> sl = new LinkedList<Stm>();
    jj_consume_token(PROC);
    t = jj_consume_token(ID);
    jj_consume_token(LPAREN);
    fl = nt_FormalList();
    jj_consume_token(RPAREN);
    jj_consume_token(LCBR);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARRAYOF:
      case BOOLEAN:
      case INT:
      case IF:
      case WHILE:
      case OUTPUT:
      case TRUE:
      case FALSE:
      case SELF:
      case NEW:
      case LPAREN:
      case NOT:
      case ISNULL:
      case LCBR:
      case INTEGER_LITERAL:
      case ID:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_9;
      }
      s = nt_Statement();
                                                                              sl.add(s);
    }
    jj_consume_token(RCBR);
   {if (true) return new ProcDecl(t.image, fl, sl);}
    throw new Error("Missing return statement in function");
  }

  final public Exp nt_PrimaryExp() throws ParseException {
  Token t;
  Var v;
  Type type;
  Exp e;
  Exp e2;
  List<Exp> el;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      t = jj_consume_token(INTEGER_LITERAL);
                        {if (true) return new ExpInteger(Integer.parseInt(t.image));}
      break;
    case TRUE:
      jj_consume_token(TRUE);
         {if (true) return new ExpTrue();}
      break;
    case FALSE:
      jj_consume_token(FALSE);
          {if (true) return new ExpFalse();}
      break;
    case ID:
      v = nt_var();
             {if (true) return new ExpVar(v);}
      break;
    case SELF:
      jj_consume_token(SELF);
         {if (true) return new ExpSelf();}
      break;
    default:
      jj_la1[13] = jj_gen;
      if (jj_2_2(2)) {
        jj_consume_token(NEW);
        jj_consume_token(ARRAYOF);
        jj_consume_token(LPAREN);
        type = nt_Type();
        jj_consume_token(RPAREN);
        jj_consume_token(LSQBR);
        e2 = nt_Exp();
        jj_consume_token(RSQBR);
                                    {if (true) return new ExpNewArray(type,e2);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NEW:
          jj_consume_token(NEW);
          jj_consume_token(OBJECT);
          t = jj_consume_token(ID);
          jj_consume_token(LPAREN);
          el = nt_ExpList();
          jj_consume_token(RPAREN);
                                                          {if (true) return new ExpNewObject(t.image,el);}
          break;
        case NOT:
          jj_consume_token(NOT);
          e2 = nt_PrimaryExp();
                           {if (true) return new ExpNot(e2);}
          break;
        case ISNULL:
          jj_consume_token(ISNULL);
          e2 = nt_PrimaryExp();
                              {if (true) return new ExpIsnull(e2);}
          break;
        case LPAREN:
          jj_consume_token(LPAREN);
          e = nt_Exp();
          jj_consume_token(RPAREN);
                               {if (true) return e;}
          break;
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public void eof() throws ParseException {
    jj_consume_token(0);
  }

  final public Var nt_var() throws ParseException {
 Token t;
    t = jj_consume_token(ID);
         {if (true) return new Var(t.image);}
    throw new Error("Missing return statement in function");
  }

  final public List<Formal> nt_FormalList() throws ParseException {
  Token t;
  Type type;
  List<Formal> fl= new LinkedList<Formal>();
  Formal f;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ARRAYOF:
    case BOOLEAN:
    case INT:
    case ID:
      type = nt_Type();
      t = jj_consume_token(ID);
                         fl.add(new Formal(type,t.image));
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMM:
          ;
          break;
        default:
          jj_la1[15] = jj_gen;
          break label_10;
        }
        f = nt_FormalRest();
                                                                              fl.add(f);
      }
                                                                                            {if (true) return fl;}
      break;
    default:
      jj_la1[16] = jj_gen;

       {if (true) return fl;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Formal nt_FormalRest() throws ParseException {
  Token t;
  Type type;
    jj_consume_token(COMM);
    type = nt_Type();
    t = jj_consume_token(ID);
                                 {if (true) return new Formal(type,t.image);}
    throw new Error("Missing return statement in function");
  }

  final public Type nt_Type() throws ParseException {
  Token t;
  Type type;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ARRAYOF:
      jj_consume_token(ARRAYOF);
      jj_consume_token(LPAREN);
      type = nt_Type();
      jj_consume_token(RPAREN);
                                          {if (true) return new TypeArray(type);}
      break;
    case BOOLEAN:
      jj_consume_token(BOOLEAN);
             {if (true) return new TypeBoolean();}
      break;
    case INT:
      jj_consume_token(INT);
         {if (true) return new TypeInt();}
      break;
    case ID:
      t = jj_consume_token(ID);
          {if (true) return new TypeClassType(t.image);}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public FieldDecl nt_FieldDecl() throws ParseException {
  Token t;
  Type type;
    type = nt_Type();
    t = jj_consume_token(ID);
    jj_consume_token(SEMICOL);
                                {if (true) return new FieldDecl(type,t.image);}
    throw new Error("Missing return statement in function");
  }

  final public Stm nt_Statement() throws ParseException {
  Token t;
  Exp e;
  StmBlock b1 , b2;
  Type type;
  Var v;
  Stm s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LCBR:
      s = nt_Block();
               {if (true) return s;}
      break;
    default:
      jj_la1[18] = jj_gen;
      if (jj_2_3(2)) {
        type = nt_Type();
        t = jj_consume_token(ID);
        jj_consume_token(SEMICOL);
                                  {if (true) return new StmVarDecl(type,t.image);}
      } else if (jj_2_4(2)) {
        v = nt_var();
        jj_consume_token(EQUALS);
        e = nt_Exp();
        jj_consume_token(SEMICOL);
                                           {if (true) return new StmAssign(v,e);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IF:
          jj_consume_token(IF);
          jj_consume_token(LPAREN);
          e = nt_Exp();
          jj_consume_token(RPAREN);
          jj_consume_token(THEN);
          b1 = nt_Block();
          jj_consume_token(ELSE);
          b2 = nt_Block();
                                                                        {if (true) return new StmIf(e,b1,b2);}
          break;
        case WHILE:
          jj_consume_token(WHILE);
          jj_consume_token(LPAREN);
          e = nt_Exp();
          jj_consume_token(RPAREN);
          jj_consume_token(DO);
          b1 = nt_Block();
                                                      {if (true) return new StmWhile(e,b1);}
          break;
        case OUTPUT:
          jj_consume_token(OUTPUT);
          e = nt_Exp();
          jj_consume_token(SEMICOL);
                               {if (true) return new StmOutput(e);}
          break;
        case TRUE:
        case FALSE:
        case SELF:
        case NEW:
        case LPAREN:
        case NOT:
        case ISNULL:
        case INTEGER_LITERAL:
        case ID:
          e = nt_PrimaryExp();
          s = nt_Beta(e);
                                   {if (true) return s;}
          break;
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public Stm nt_Beta(Exp e1) throws ParseException {
  Token t;
  Exp e2 ,e3;
  List<Exp> el;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LSQBR:
      jj_consume_token(LSQBR);
      e2 = nt_Exp();
      jj_consume_token(RSQBR);
      jj_consume_token(EQUALS);
      e3 = nt_Exp();
      jj_consume_token(SEMICOL);
                                                          {if (true) return new StmArrayAssign(e1,e2,e3);}
      break;
    case PERIOD:
      jj_consume_token(PERIOD);
      t = jj_consume_token(ID);
      jj_consume_token(LPAREN);
      el = nt_ExpList();
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOL);
                                                             {if (true) return new StmCall(e1,t.image,el);}
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public StmBlock nt_Block() throws ParseException {
  Stm s;
  List<Stm> sl = new LinkedList<Stm>();
    jj_consume_token(LCBR);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARRAYOF:
      case BOOLEAN:
      case INT:
      case IF:
      case WHILE:
      case OUTPUT:
      case TRUE:
      case FALSE:
      case SELF:
      case NEW:
      case LPAREN:
      case NOT:
      case ISNULL:
      case LCBR:
      case INTEGER_LITERAL:
      case ID:
        ;
        break;
      default:
        jj_la1[21] = jj_gen;
        break label_11;
      }
      s = nt_Statement();
                          sl.add(s);
    }
    jj_consume_token(RCBR);
                                              {if (true) return new StmBlock(sl);}
    throw new Error("Missing return statement in function");
  }

  final public Exp nt_Exp() throws ParseException {
  Exp e1;
  Exp e2;
    e1 = nt_PrimaryExp();
    e2 = nt_Alpha(e1);
                                     {if (true) return e2;}
    throw new Error("Missing return statement in function");
  }

  final public Exp nt_Alpha(Exp e1) throws ParseException {
  Token t;
  List<Exp> el;
  Exp e2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OP:
      t = jj_consume_token(OP);
      e2 = nt_PrimaryExp();
    if(t.image == "and"){
      {if (true) return new ExpOp(e1, ExpOp.Op.AND,e2);}
    }else if(t.image == "div"){
      {if (true) return new ExpOp(e1, ExpOp.Op.DIV,e2);}
    }else if(t.image == "+"){
      {if (true) return new ExpOp(e1, ExpOp.Op.PLUS,e2);}
    }else if(t.image == "-"){
      {if (true) return new ExpOp(e1, ExpOp.Op.MINUS,e2);}
    }else if(t.image == "=="){
      {if (true) return new ExpOp(e1, ExpOp.Op.EQUALS,e2);}
    }else if(t.image == "*"){
      {if (true) return new ExpOp(e1, ExpOp.Op.TIMES,e2);}
    }else{
      {if (true) return new ExpOp(e1, ExpOp.Op.LESSTHAN,e2);}
    }
      break;
    case LSQBR:
      jj_consume_token(LSQBR);
      e1 = nt_Exp();
      jj_consume_token(RSQBR);
                             {if (true) return e1;}
      break;
    default:
      jj_la1[22] = jj_gen;
      if (jj_2_5(2)) {
        jj_consume_token(PERIOD);
        jj_consume_token(LENGTH);
                                {if (true) return new ExpArrayLength(e1);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PERIOD:
          jj_consume_token(PERIOD);
          t = jj_consume_token(ID);
          jj_consume_token(LPAREN);
          el = nt_ExpList();
          jj_consume_token(RPAREN);
                                                 {if (true) return new ExpCall(e1,t.image,el);}
          break;
        default:
          jj_la1[23] = jj_gen;

       {if (true) return e1;}
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public List<Exp> nt_ExpList() throws ParseException {
  Exp e;
  List<Exp> el = new LinkedList<Exp>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
    case FALSE:
    case SELF:
    case NEW:
    case LPAREN:
    case NOT:
    case ISNULL:
    case INTEGER_LITERAL:
    case ID:
      e = nt_Exp();
             el.add(e);
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMM:
          ;
          break;
        default:
          jj_la1[24] = jj_gen;
          break label_12;
        }
        e = nt_ExpRest();
                                         el.add(e);
      }
                                                        {if (true) return el;}
      break;
    default:
      jj_la1[25] = jj_gen;

                                                                          {if (true) return el;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Exp nt_ExpRest() throws ParseException {
  Exp e;
    jj_consume_token(COMM);
    e = nt_Exp();
                     {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_3_1() {
    if (jj_scan_token(CLASS)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LCBR)) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(EQUALS)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(PERIOD)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  private boolean jj_3R_13() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_15()) {
    jj_scanpos = xsp;
    if (jj_3R_16()) {
    jj_scanpos = xsp;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_scan_token(ARRAYOF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(ARRAYOF)) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public MooplParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[26];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xffffff00,0xffffff00,0xffffff00,0x100,0x400,0xe000,0x300,0xe000,0x300,0x400,0x300,0xfa9e000,0xfa9e000,0x3800000,0xc000000,0x0,0xe000,0xe000,0x0,0xfa90000,0x40000000,0xfa9e000,0x40000000,0x0,0x0,0xf800000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x7ff,0xff,0x7ff,0x0,0x0,0x400,0x0,0x400,0x0,0x0,0x0,0x50b,0x50b,0x500,0x3,0x4,0x400,0x400,0x8,0x503,0x20,0x50b,0x200,0x20,0x4,0x503,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[5];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MooplParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MooplParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MooplParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MooplParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MooplParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MooplParser(MooplParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MooplParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[43];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 26; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 43; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 5; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

  }
